data = """MOUNT:
PAD;
KVA RATING:
1500 KVA;
PHASE:
3 PH;
APPLICATION PRIMARY VOLT:
34500 V AC;
ACTUAL PRIMARY VOLT:
34.5K V AC;
SECONDARY VOLT:
4160/480 V AC;
FREQUENCY:
60 HZ;
PRIMARY BIL RATING:
150 KV;
SECONDARY BIL RATINGS:
30 KV;
VECTOR GROUP:
YYYN0;
PRIMARY BUSHINGS:
(3) LOAD BREAK BUSHING INSERT;
SECONDARY BUSHINGS:
(3) LOAD BREAK BUSHING INSERT FOR 4160
V, (4) ENCLOSED 4-HOLES SPADE TERMINATI ONS FOR 480 V;
PRIMARY CONNECTIONS:
LOADBREAK ELBOW TERMINATION;
SECONDARY CONNECTIONS:
LOAD BREAK BUSHING INSERT (FOR 4160 V),
ENCLOSED SPADE TERMINALS;
STANDARD/SPECIFICATION:
51-SMSS-6;
ADDITIONAL DATA:
RADIAL FEED, SAMPLE SER NO TBT 7525-0102
WESTINGHOUSE (FM):
P/N#RSL/34500 V
APPLICATOIN:
INSTALLED AT 31CC IN JUBAIL INDUSTRIAL CITY IN MDNOD NORTH AREA.

"""
#A = data.splitlines()
A = data.split("\n")
print(A)
B = str(A).replace("n"," ")
print(B)
C = str(A).replace("\\"," ")
print(C)

#A = data.splitlines()
print(len(A))


def Convert(lst):
    res_dct = {lst[i]: lst[i + 1] for i in range(0, len(lst), 2)}
    return res_dct
         
# Driver code
#lst = ['AMPERAGE:', '2500 A;', 'CONNECTION:', 'DRAWABLE;', 'INTERRUPTING CAPACITY:', '31.5 KA;', 'KV RATING:', '33 KV;', 'PHASE:', '3 PHASE;', 'STANDARD/SPECIFICATION:', 'IEC 56;']
lst = A 
Z = (Convert(lst))
print(Z)
print(Z.keys())
AA = Z.values()
ZZ = str(AA)
ZZZ = ZZ.replace(";"," ")
print(ZZZ)
