# Tranformer

1 - MOUNT:PAD;
2 - KVA RATING:1500 KVA;
3 - PHASE:3 PH;
4 - APPLICATION PRIMARY VOLT:34500 V AC;
5 - ACTUAL PRIMARY VOLT:34.5K V AC;
6 - SECONDARY VOLT:4160/480 V AC;
7 - FREQUENCY:60 HZ;
8 - PRIMARY BIL RATING:150 KV;
9 - SECONDARY BIL RATINGS:30 KV;
10 - VECTOR GROUP:YYYN0;
11 - PRIMARY BUSHINGS:(3) LOAD BREAK BUSHING INSERT;
12 - SECONDARY BUSHINGS:(3) LOAD BREAK BUSHING INSERT FOR 4160 V, (4) ENCLOSED 4-HOLES SPADE TERMINATIONS FOR 480 V;
13 - PRIMARY CONNECTIONS:LOADBREAK ELBOW TERMINATION;
14 - SECONDARY CONNECTIONS:LOAD BREAK BUSHING INSERT (FOR 4160 V),ENCLOSED SPADE TERMINALS;
15 - STANDARD/SPECIFICATION:51-SMSS-6;
16 - ADDITIONAL DATA:RADIAL FEED, SAMPLE SER NO TBT 7525-0102
17 - WESTINGHOUSE (FM):P/N#RSL/34500 V
18 - APPLICATOIN:INSTALLED AT 31CC IN JUBAIL INDUSTRIAL CITY IN MDNOD NORTH AREA.
19 - The VENDOR/MANUFACTURER shall bear all expenses but not limited to the following:
20 - FACTORY ACCEPTANCE TEST (FAT):
